name: MaliUtils
version: '1.0'
main: io.github.maliciousfiles.maliUtils.MaliUtils
api-version: '1.21'
authors: [ MaliciousFiles ]
description: A plugin with various *utilities* for a Minecraft server admin.
commands:
  vanish:
    description: Vanish from other players.
    usage: /vanish [player]
    permission: op
  listvanish:
    description: List all players that are vanished.
    usage: /listvanish
    permission: op
    aliases: [lv]
  smite:
    description: Smite a player into the air.
    usage: /smite <player>
    permission: op
  invsee:
    description: View the inventory of another player.
    usage: /invsee <player>
    permission: op
  swap:
    description: Swap the location of two players.
    usage: /swap <player1> <player2>
    permission: op
  healthlink:
    description: Manage healthlink groups.
    usage: /healthlink <create/delete/join/leave/set> <group/player> [player/health]
    permission: op
    aliases: [hl]
  demon:
    description: Summon a demon animal.
    usage: /demon <facade>
    permission: op
  freeze:
    description: Freeze a player in place.
    usage: /freeze <player>
    permission: op