name: MaliUtils
version: '1.0'
main: io.github.maliciousfiles.maliUtils.MaliUtils
api-version: '1.21'
authors: [ MaliciousFiles ]
description: A plugin with various *utilities* for a Minecraft server admin.
